language: node_js

node_js: 10

stages:
  - test
  - build

# 打包
build:
  stage: build
  install: npm install
  script:
    - npm run build
    - npm run doc
# 测试
test:
  stage: test
  install: skip
  script:
    - npm run test
    - npm run cover
  after_success:
    - npm run coveralls

  deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
# 发布
publish:
  only:
    - tags
  tags:
    - your-runner-tag
  script:
    - echo "NPM Deploying Started ..."
    - npm version
    - npm run build
    - echo "NPM Building Finished."
  # publish:
  #     provider: npm
  #     email: chengjunchao@hotmail.com
  #     api_key: "$NPM_TOKEN"
  #     skip_cleanup: true
  #     on:
  #       all_branches: true
