language: node_js

node_js: 10

os:
  - linux

stages:
  - test
  - build

   
jobs:
  include:
    - stage: build
      script:
       - npm run build
# 测试
    -stage: test
      install: skip
      script:
        - npm run test
        - npm run cover
      after_success:
        - npm run coveralls

publish:
      only:
        - tags
      tags:
        - your-runner-tag
      script:
          - echo "NPM Deploying Started ..."
          - npm version
          - npm run build
          - echo "NPM Building Finished."
      # publish:
      #     provider: npm
      #     email: chengjunchao@hotmail.com
      #     api_key: "$NPM_TOKEN"
      #     skip_cleanup: true
      #     on:
      #       all_branches: true

