# Designated language. https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

# Install dependence
install:
  - npm install

# Cache the node_modules folder and don't need to download and install all npm packages every time.
cache:
  directories:
    - node_modules
# Specify the node version.
node_js:
  - '12'
# Perform builds only on the specified branch.  https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
branches:
  only:
    - master
# The script to execute.
script:
  - npm run test
  - npm run build
  - npm run doc
  - cp ./_config.yml ./docs/_config.yml
  - git init
  - git add -A
  - git symbolic-ref --short HEAD
  - git commit -m "docs:update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/citrusjunoss/qzd-utils.git" master:gh_page
deploy:
  provider: npm
  email: chengjunchao@hotmail.com
  api_key: ${NPM_TOKEN}
  on:
    tags: true
    repo: citrusjunoss/qzd-utils
# Build doc report cover
after_success:
  - NODE_COVERALLS_DEBUG=1 npm run cover
# Configure to send notifications when the build fails. https://docs.travis-ci.com/user/notifications
# notifications:
#   webhooks:
#     urls:
#       - https://www.travisbuddy.com/
#     on_success: never # Successful build does not send mail.
#     on_failure: always # Build failure always sends a message.

