language: node_js

node_js: 10

language: node_js

node_js: 10

stages:
  - test
  - build
  - deploy
# 打包
build:
  stage: build
  install: npm install
  script:
    - npm run build
    - npm run doc
# 测试
test:
  stage: test
  install: skip
  script:
    - npm run test
    - npm run cover
  after_success:
    - npm run coveralls
# 发布
publish:
      only:
        - tags
      tags:
        - your-runner-tag
      script:
          - echo "NPM Deploying Started ..."
          - npm version
          - npm run build
          - echo "NPM Building Finished."
# release
deploy:
  provider: releases
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/lib/index.js"
  api_key:
    secure: "$API_KEY"
  on:
    tags: true #发布  tag版 时才进行发包   
    draft: false # 不发表drafs
          
      # publish:
      #     provider: npm
      #     email: chengjunchao@hotmail.com
      #     api_key: "$NPM_TOKEN"
      #     skip_cleanup: true
      #     on:
      #       all_branches: true

