language: node_js

node_js: 12

jobs:
  include:
    - stage: test
      install: npm install
      test:
        script:
          - npm run test
          - npm run cover
        after_success:
          - echo "NPM coveralls Started ..."
          - npm run coveralls
    - stage: build
      build:
        install: skip
        script:
          - npm run build
          - npm run doc
          - echo "build done!"
    - stage: docs
      docs:
        provider: pages
        cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        script:
          - echo 'move config 文件'
        target_branch: gh_page
        on:
          branch: master
    - stage: deploy
      deploy:
        provider: npm
        email: chengjunchao@hotmail.com
        api_key: '$NPM_TOKEN'
        cleanup: true
        on:
          tags: true
          branch: all
        tag: latest
        # condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
