name: gh_pages

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Npm install
        run: npm install
      - name: BuildDocs
        run: npm run doc
      - name: CopyConfig
        run: cp ./_config.yml ./docs/_config.yml
      - name: DeployPages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-page # default: gh-pages
          publish_dir: ./public
